name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'shard.yml'
      - 'shard.lock'
      - 'src/**'
      - 'spec/**'

jobs:
  spec:
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-22.04
    steps:
      - name: Install RabbitMQ
        run: apt-get update && apt-get install -y rabbitmq-server

      - name: Start RabbitMQ
        run: RABBITMQ_PID_FILE=/tmp/rabbitmq.pid rabbitmq-server -detached

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install shards
        run: sed -i '/ameba/d' shard.yml && shards install

      - name: Wait for RabbitMQ to start
        run: rabbitmqctl wait /tmp/rabbitmq.pid

      - name: Run tests
        run: crystal spec --order random

  lint:
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: shards install
      - run: bin/ameba

  format:
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: crystal tool format --check
